import React from 'react';

import './globals.css';

import type { Metadata } from 'next';
import { ApolloWrapper } from '@/lib/apollo/wrapper';
import { SpeedInsights } from '@vercel/speed-insights/next';
import { Analytics } from '@vercel/analytics/next';
import PageLoadingProvider from '@/components/page-loading-provider';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body>
        <PageLoadingProvider>
          <ApolloWrapper>{children}</ApolloWrapper>
        </PageLoadingProvider>
        <SpeedInsights />
        <Analytics />
      </body>
    </html>
  );
}
