services:
  traefik:
    image: traefik:v3.1
    command: --configFile=/etc/traefik/traefik.yml
    ports:
      # HTTP
      - "80:80"
      # HTTPS
      - "443:443"
      # traefik dashboard
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - letsencrypt:/letsencrypt
      - ./traefik.yml:/etc/traefik/traefik.yml
    networks:
      - traefik

networks:
  traefik:
    external: true